[profile.dev.package.png]
opt-level = 3
[profile.dev.package.image]
opt-level = 3
[profile.dev.package.fdeflate]
opt-level = 3
[profile.dev.package.flate2]
opt-level = 3
[profile.dev.package.miniz_oxide]
opt-level = 3
[profile.dev.package.simd-adler32]
opt-level = 3
[profile.dev.package.crc32fast]
opt-level = 3
[profile.dev.package.base64]
opt-level = 3
[profile.dev.package.serde_json]
opt-level = 3
[profile.dev.package.i-slint-backend-testing]
opt-level = 3
